import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { Suspense } from "react";
import DrawerAppBar from "./Header";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider, Container } from "@mui/material";
import theme from "@/theme";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ key: 'css' }}>
            <ThemeProvider theme={theme}>
            <DrawerAppBar/>
                <Container>
                {children}
                </Container>
                <Footer/>
            </ThemeProvider>
         </AppRouterCacheProvider>
          </body>
    </html>
  );
}
